# Generated by Django 4.1.7 on 2024-03-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casierjudiciaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casierjudiciaire",
            name="etat",
            field=models.CharField(
                choices=[
                    ("traitement", "En cours de traitement"),
                    ("termine", "Terminé"),
                ],
                default="traitement",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="casierjudiciaire",
            name="etat_familiale",
            field=models.CharField(
                choices=[
                    ("celibataire", "Célibataire"),
                    ("marie", "Marié"),
                    ("divorce", "Divorcé"),
                    ("veuf_veuve", "Veuf ou Veuve"),
                ],
                default="celibataire",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="casierjudiciaire",
            name="genre",
            field=models.CharField(
                choices=[("homme", "Homme"), ("femme", "Femme")],
                default="homme",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="casierjudiciaire",
            name="profession",
            field=models.CharField(
                choices=[
                    ("etudiant", "Etudiant"),
                    ("travailleur", "Travailleur"),
                    ("chomeur", "Chomeur"),
                    ("retraitee", "Retraité"),
                ],
                default="etudiant",
                max_length=255,
            ),
        ),
    ]
