# Generated by Django 4.1.7 on 2024-07-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casierjudiciaire", "0003_localitebackoffice_casierjudiciaire_localite"),
    ]

    operations = [
        migrations.AddField(
            model_name="localitebackoffice",
            name="code_localite",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
