# Generated by Django 4.1.7 on 2024-07-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casierjudiciaire", "0004_localitebackoffice_code_localite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casierjudiciaire",
            name="code_demande",
            field=models.CharField(max_length=255),
        ),
    ]
