# Generated by Django 4.1.7 on 2024-07-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casierjudiciaire", "0005_alter_casierjudiciaire_code_demande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casierjudiciaire",
            name="code_demande",
            field=models.PositiveIntegerField(),
        ),
    ]
