# Generated by Django 4.1.7 on 2024-07-02 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("casierjudiciaire", "0006_alter_casierjudiciaire_code_demande"),
    ]

    operations = [
        migrations.AddField(
            model_name="casierjudiciaire",
            name="backoffice_received",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="casierjudiciaire",
            name="localite",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="casierjudiciaire.localitebackoffice",
            ),
            preserve_default=False,
        ),
    ]
