PROFESSION_TYPES_CHOICES = [
    ('etudiant',"Etudiant"),
    ('travailleur',"Travailleur"),
    ('chomeur',"Chomeur"),
    ('retraitee',"Retraité")
]

ETAT_DEMANDE_TYPES_CHOICES = [
    ('traitement','En cours de traitement'),
    ('termine',"Terminé")
]

GENRE_CHOICES = [
    ("homme", "Homme"),
    ("femme", "Femme")
]

STATUS_MATRINONIAL_CHOICES = [
    ('celibataire', "Célibataire"),
    ('marie', 'Marié'),
    ('divorce',"Divorcé"),
    ('veuf_veuve',"Veuf ou Veuve")
]

PAYS_CODES_CHOICES = [
("Afghanistan","Afghanistan"),
("Afrique_centrale","Afrique Centrale"),
("Afrique_du_sud","Afrique du Sud"),
("Albanie","Albanie"),
("Algerie","Algerie"),
("Allemagne","Allemagne"),
("Andorre","Andorre"),
("Angola","Angola"),
("Anguilla","Anguilla"),
("Arabie_saoudite","Arabie Saoudite"),
("Argentine","Argentine"),
("Armenie","Armenie"),
("Australie","Australie"),
("Autriche","Autriche"),
("Azerbaidjan","Azerbaidjan"),

("Bahamas","Bahamas"),
("Bangladesh","Bangladesh"),
("Barbade","Barbade"),
("Bahrein","Bahrein"),
("Belgique","Belgique"),
("Belize","Belize"),
("Benin","Benin"),
("Bermudes","Bermudes"),
("Bielorussie","Bielorussie"),
("Bolivie","Bolivie"),
("Botswana","Botswana"),
("Bhoutan","Bhoutan"),
("Boznie_herzegovine","Boznie Herzegovine"),
("Bresil","Bresil"),
("Brunei","Brunei"),
("Bulgarie","Bulgarie"),
("Burkina_faso","Burkina Faso"),
("Burundi","Burundi"),

("Caiman","Caiman"),
("Cambodge","Cambodge"),
("Cameroun","Cameroun"),
("Canada","Canada"),
("Canaries","Canaries"),
("Cap_vert","Cap Vert"),
("Chili","Chili"),
("Chine","Chine"),
("Chypre","Chypre"),
("Colombie","Colombie"),
("Comores","Colombie"),
("Congo","Congo"),
("Congo_democratique","Congo Democratique"),
("Cook","Cook"),
("Coree_du_nord","Coree du Nord"),
("Coree_du_sud","Coree du Sud"),
("Costa_rica","Costa Rica"),
("Cote_d_ivoire","Côte d'Ivoire"),
("Croatie","Croatie"),
("Cuba","Cuba"),

("Danemark","Danemark"),
("Djibouti","Djibouti"),
("Dominique","Dominique"),

("Egypte","Egypte"),
("Emirats_arabes_unis","Emirats Arabes Unis"),
("Equateur","Equateur"),
("Erythree","Erythree"),
("Espagne","Espagne"),
("Estonie","Estonie"),
("Etats_unis","Etats Unis"),
("Ethiopie","Ethiopie"),

("Falkland","Falkland"),
("Feroe","Feroe"),
("Fidji","Fidji"),
("Finlande","Finlande"),
("France","France"),

("Gabon","Gabon"),
("Gambie","Gambie"),
("Georgie","Georgie"),
("Ghana","Ghana"),
("Gibraltar","Gibraltar"),
("Grece","Grece"),
("Grenade","Grenade"),
("Groenland","Groenland"),
("Guadeloupe","Guadeloupe"),
("Guam","Guam"),
("Guatemala","Guatemala"),
("Guernesey","Guernesey"),
("Guinee","Guinee"),
("Guinee_bissau","Guinee_Bissau"),
("Guinee_equatoriale","Guinee Equatoriale"),
("Guyana","Guyana"),
("Guyane_francaise","Guyane Francaise"),

("Haiti","Haiti"),
("Hawaii","Hawaii"),
("Honduras","Honduras"),
("Hong_kong","Hong kong"),
("Hongrie","Hongrie"),

("Inde","Inde"),
("Indonesie","Indonesie"),
("Iran","Iran"),
("Iraq","Iraq"),
("Irlande","Irlande"),
("Islande","Islande"),
("Israel","Israel"),
("Italie","italie"),

("Jamaique","Jamaique"),
("Jan_mayen","Jan Mayen"),
("Japon","Japon"),
("Jersey","Jersey"),
("Jordanie","Jordanie"),

("Kazakhstan","Kazakhstan"),
("Kenya","Kenya"),
("Kirghizstan","Kirghizistan"),
("Kiribati","Kiribati"),
("Koweit","Koweit"),

("Laos","Laos"),
("Lesotho","Lesotho"),
("Lettonie","Lettonie"),
("Liban","Liban"),
("Liberia","Liberia"),
("Liechtenstein","Liechtenstein"),
("Lituanie","Lituanie"),
("Luxembourg","Luxembourg"),
("Lybie","Lybie"),

("Macao","Macao"),
("Macedoine","Macedoine"),
("Madagascar","Madagascar"),
("Madère","Madère"),
("Malaisie","Malaisie"),
("Malawi","Malawi"),
("Maldives","Maldives"),
("Mali","Mali"),
("Malte","Malte"),
("Man","Man"),
("Mariannes_du_nord","Mariannes du Nord"),
("Maroc","Maroc"),
("Marshall","Marshall"),
("Martinique","Martinique"),
("Maurice","Maurice"),
("Mauritanie","Mauritanie"),
("Mayotte","Mayotte"),
("Mexique","Mexique"),
("Micronesie","Micronesie"),
("Midway","Midway"),
("Moldavie","Moldavie"),
("Monaco","Monaco"),
("Mongolie","Mongolie"),
("Montserrat","Montserrat"),
("Mozambique","Mozambique"),

("Namibie","Namibie"),
("Nauru","Nauru"),
("Nepal","Nepal"),
("Nicaragua","Nicaragua"),
("Niger","Niger"),
("Nigeria","Nigeria"),
("Niue","Niue"),
("Norfolk","Norfolk"),
("Norvege","Norvege"),
("Nouvelle_caledonie","Nouvelle Caledonie"),
("Nouvelle_zelande","Nouvelle Zelande"),

("Oman","Oman"),
("Ouganda","Ouganda"),
("Ouzbekistan","Ouzbekistan"),

("Pakistan","Pakistan"),
("Palau","Palau"),
("Palestine","Palestine"),
("Panama","Panama"),
("Papouasie_nouvelle_guinee","Papouasie Nouvelle Guinee"),
("Paraguay","Paraguay"),
("Pays_bas","Pays Bas"),
("Perou","Perou"),
("Philippines","Philippines"),
("Pologne","Pologne"),
("Polynesie","Polynesie"),
("Porto_rico","Porto Rico"),
("Portugal","Portugal"),

("Qatar","Qatar"),

("Republique_dominicaine","Republique Dominicaine"),
("Republique_tcheque","Republique Tcheque"),
("Reunion","Reunion"),
("Roumanie","Roumanie"),
("Royaume_uni","Royaume Uni"),
("Russie","Russie"),
("Rwanda","Rwanda"),

("Sahara_occidental","Sahara Occidental"),
("Sainte_lucie","Sainte Lucie"),
("Saint_marin","Saint Marin"),
("Salomon","Salomon"),
("Salvador","Salvador"),
("Samoa_occidentales","Samoa Occidentales"),
("Samoa_americaine","Samoa Americaine"),
("Sao_tome_et_principe","Sao Tome et Principe"),
("Senegal","Senegal"),
("Seychelles","Seychelles"),
("Sierra_Leone","Sierra Leone"),
("Singapour","Singapour"),
("Slovaquie","Slovaquie"),
("Slovenie","Slovenie"),
("Somalie","Somalie"),
("Soudan","Soudan"),
("Sri_lanka","Sri Lanka"),
("Suede","Suede"),
("Suisse","Suisse"),
("Surinam","Surinam"),
("Swaziland","Swaziland"),
("Syrie","Syrie"),

("Tadjikistan","Tadjikistan"),
("Taiwan","Taiwan"),
("Tonga","Tonga"),
("Tanzanie","Tanzanie"),
("Tchad","Tchad"),
("Thailande","Thailande"),
("Tibet","Tibet"),
("Timor_oriental","Timor Oriental"),
("Togo","Togo"),
("Trinite_et_tobago","Trinite et Tobago"),
("Tristan_de_cunha","Tristan de cuncha"),
("Tunisie","Tunisie"),
("Turkmenistan","Turmenistan"),
("Turquie","Turquie"),

("Ukraine","Ukraine"),
("Uruguay","Uruguay"),

("Vanuatu","Vanuatu"),
("Vatican","Vatican"),
("Venezuela","Venezuela"),
("Vierges_americaines","Iles Vierges Americaines"),
("Vierges_britanniques","Iles Vierges Britanniques"),
("Vietnam","Vietnam"),

("Wake","Wake"),
("Wallis_et_futuma","Wallis et Futuma"),

("Yemen","Yemen"),
("Yougoslavie","Yougoslavie"),

("Zambie","Zambie"),
("Zimbabwe","Zimbabwe"),
]

